# fly.toml app configuration file generated for gamerstore on 2023-07-10T00:08:05-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gamerstore"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
